---
- name: Config para estrutura base do LAB1
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Install pre-requisitos
      ansible.builtin.yum:
        name:  
          - git
        state: present
    
    - name: Install checkmk
      ansible.builtin.yum:
        name:
          - https://download.checkmk.com/checkmk/2.2.0p22/check-mk-raw-2.2.0p22-el9-38.x86_64.rpm
        state: present

    - name: Show SO distribution
      debug:
        msg: "SO= {{ ansible_facts['ansible_distribution'] }}, {{ ansible_facts['ansible_distribution_version'] }}"