---
- name: Config para estrutura base do LAB1
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Install pre-requisitos
      ansible.builtin.yum:
        name:  
          - git
        state: present
    
    - name: Install checkmk
      ansible.builtin.yum:
        name:
          - https://download.checkmk.com/checkmk/2.2.0p22/check-mk-raw-2.2.0p22-el9-38.x86_64.rpm
        state: present
        disable_gpg_check: yes
      when: ansible_distribution == "RedHat"

    - name: Create a site
      ansible.builtin.shell: |
        omd create lab1_asf
      register: create_output

    - name: Show site information
      ansible.builtin.debug:
        msg: create_output
        