---
- name: Mariadb config for Lab1-asf
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Create database
      become: yes
      ansible.builtin.command: sudo mysql -e "CREATE DATABASE asfapi;"
      tags: create database

    - name: Create user
      become: yes
      ansible.builtin.command: sudo mysql -e "CREATE USER 'master'@'%' IDENTIFIED BY '{{mysql_user}}';"
      tags: create user

    - name: Grant privileges
      become: yes
      ansible.builtin.command: sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'master'@'%';"
      tags: grant-privileges

    - name: Flush privileges
      become: yes
      ansible.builtin.command: sudo mysql -e "FLUSH PRIVILEGES;"
      tags: flush-privileges

    - name: Alterar a linha bind-address
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'