AWSTemplateFormatVersion: "2010-09-09"
Description: Create Infrastructure for LAB1-asf

Resources:
  CMKPrincipal:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-079db87dc4c10ac91  # Amazon Linux 2023
      InstanceType: t2.micro
      KeyName: terraform-ssh-key
      IamInstanceProfile: EC2-SSM-Role
      # SecurityGroupIds:
      #   - sg-0badf67fc724fbf0a
      #SubnetId: subnet-0027573722f821560
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          SubnetId: subnet-0027573722f821560
      Tags:
        - Key: Name
          Value: "CMKPrincipal" 
      UserData:
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y

  MysqlNode1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-079db87dc4c10ac91  # Amazon Linux 2023
      InstanceType: t2.micro
      KeyName: terraform-ssh-key
      IamInstanceProfile: EC2-SSM-Role
      SecurityGroupIds:
        - sg-0badf67fc724fbf0a
      SubnetId: subnet-0027573722f821560
      Tags:
        - Key: Name
          Value: "MySQL-Node1"
      UserData:
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y

  MysqlNode2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-079db87dc4c10ac91  # Amazon Linux 2023
      InstanceType: t2.micro
      KeyName: terraform-ssh-key
      IamInstanceProfile: EEC2-SSM-Role
      SecurityGroupIds:
        - sg-0badf67fc724fbf0a
      SubnetId: subnet-0027573722f821560
      Tags:
        - Key: Name
          Value: "MySQL-Node2"
      UserData:
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y
