AWSTemplateFormatVersion: "2010-09-09"
Description: Create Infrastructure for LAB1-asf

Resources:
  CMKMaster:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fe630eb857a6ec83  # Amazon Linux 2023
      InstanceType: t2.micro
      KeyName: lab1-ssh-hmg
      IamInstanceProfile: EC2-SSM-Role
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          SubnetId: subnet-06ab5911aacc1f1fa
      Tags:
        - Key: Name
          Value: "CMKMaster" 
      UserData:
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y