AWSTemplateFormatVersion: "2010-09-09"
Description: Create Infrastructure for LAB1-asf

Parameters:
  AMIVersionRedHat9:
    Type: String
    Default: "ami-0fe630eb857a6ec83"
  AMIVersionUbuntu20:
    Type: String
    Default: "ami-06aa3f7caf3a30282"


Resources:
  CMKMaster:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIVersionUbuntu20
      InstanceType: t2.micro
      KeyName: lab1-ssh-hmg
      IamInstanceProfile: EC2-SSM-Role
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          SubnetId: subnet-06ab5911aacc1f1fa
      Tags:
        - Key: Name
          Value: "CMKMaster" 
      UserData:
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y