AWSTemplateFormatVersion: "2010-09-09"
Description: Create Infrastructure for LAB1-asf

Resources:
  CMKMaster:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-079db87dc4c10ac91  # Amazon Linux 2023
      InstanceType: t2.micro
      KeyName: lab1-ssh
      IamInstanceProfile: SSM-EC2-Role
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          SubnetId: subnet-093dffa281cc643bb
      Tags:
        - Key: Name
          Value: "CMKMaster" 
      UserData:
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y