AWSTemplateFormatVersion: "2010-09-09"
Description: Create Infrastructure for LAB1-asf

Parameters:
  SubnetId:
    Type: String
    Description: Id da subnet onde a instância será criada
  SSMRoleEc2:
    Type: String
    Description: Nome da Role SSM que fornece acesso a EC2

Resources:
  CMKMaster:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-079db87dc4c10ac91  # Amazon Linux 2023
      InstanceType: t2.micro
      KeyName: lab1-ssh
      IamInstanceProfile: !Ref SSMRoleEc2
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: "CMKMaster" 
      UserData:
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y